/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { DidString } from '@atproto/lex'

export class AccountSchema extends BaseModel {
  static $columns = ['createdAt', 'did', 'handle', 'hidden', 'isActive', 'status', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare did: DidString
  @column()
  declare handle: string
  @column()
  declare hidden: boolean
  @column()
  declare isActive: boolean
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OauthSessionSchema extends BaseModel {
  static $columns = ['sub', 'updatedAt', 'value'] as const
  $columns = OauthSessionSchema.$columns
  @column({ isPrimary: true })
  declare sub: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class OauthStateSchema extends BaseModel {
  static $columns = ['key', 'updatedAt', 'value'] as const
  $columns = OauthStateSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class ProfileSchema extends BaseModel {
  static $columns = ['cid', 'createdAt', 'description', 'did', 'displayName', 'indexedAt', 'updatedAt'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare cid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare did: DidString
  @column()
  declare displayName: string | null
  @column.dateTime()
  declare indexedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}
