/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'did',
    'handle',
    'hidden',
    'isActive',
    'status',
    'updatedAt',
  ] as const
  $columns = AccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare did: string
  @column()
  declare handle: string | null
  @column()
  declare hidden: boolean
  @column()
  declare isActive: boolean
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OauthSessionSchema extends BaseModel {
  static $columns = ['sub', 'updatedAt', 'value'] as const
  $columns = OauthSessionSchema.$columns
  @column()
  declare sub: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class OauthStateSchema extends BaseModel {
  static $columns = ['key', 'updatedAt', 'value'] as const
  $columns = OauthStateSchema.$columns
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class ProfileSchema extends BaseModel {
  static $columns = ['cid', 'createdAt', 'did', 'indexedAt', 'record', 'updatedAt'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare cid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare did: string
  @column.dateTime()
  declare indexedAt: DateTime | null
  @column()
  declare record: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuestionSchema extends BaseModel {
  static $columns = [
    'authorDid',
    'cid',
    'contextCid',
    'contextType',
    'contextUri',
    'createdAt',
    'indexedAt',
    'record',
    'rkey',
    'updatedAt',
    'uri',
  ] as const
  $columns = QuestionSchema.$columns
  @column()
  declare authorDid: string
  @column()
  declare cid: string | null
  @column()
  declare contextCid: string | null
  @column()
  declare contextType: string | null
  @column()
  declare contextUri: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare indexedAt: DateTime | null
  @column()
  declare record: string
  @column()
  declare rkey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uri: string
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}
