/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.questionable.waitlist.approval'

export { $nsid }

/** Created when waitlist request to join Questionable.fyi has been approved. Record key is the DID of the approved account. */
type Main = {
  $type: 'fyi.questionable.waitlist.approval'
  createdAt: l.DatetimeString

  /**
   * The AT URI of the fyi.questionable.waitlist.request that was approved; Optional as to allow us to pre-approve accounts without needing them to explicitly request to join.
   */
  request?: l.AtUriString
}

export type { Main }

/** Created when waitlist request to join Questionable.fyi has been approved. Record key is the DID of the approved account. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    createdAt: l.string({ format: 'datetime' }),
    request: l.optional(l.string({ format: 'at-uri' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
