/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextContent from '../richtext/content.defs.js'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'fyi.questionable.graph.question'

export { $nsid }

/** A question asked on questionable.fyi */
type Main = {
  $type: 'fyi.questionable.graph.question'
  createdAt: l.DatetimeString

  /**
   * A short summary of the question
   */
  summary: string
  content: RichtextContent.Main

  /**
   * Indicates human language of the primary text content.
   */
  languages?: l.LanguageString[]

  /**
   * Indicates the context in which this question was asked. Currently only fyi.questionable.actor.profile
   */
  contextRef?: RepoStrongRef.Main
}

export type { Main }

/** A question asked on questionable.fyi */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    createdAt: l.string({ format: 'datetime' }),
    summary: l.string({ maxGraphemes: 300, maxLength: 3000, minLength: 1 }),
    content: l.ref<RichtextContent.Main>((() => RichtextContent.main) as any),
    languages: l.optional(
      l.array(l.string({ format: 'language' }), { maxLength: 3 }),
    ),
    contextRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
