/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.questionable.actor.profile'

export { $nsid }

/**
 * A declaration of a Questionable account profile.
 */
type Main = {
  $type: 'fyi.questionable.actor.profile'
  displayName?: string
  createdAt?: l.DatetimeString
}

export type { Main }

/**
 * A declaration of a Questionable account profile.
 */
const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
