/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'
import * as RichtextContent from './richtext/content.defs.js'

const $nsid = 'fyi.questionable.answer'

export { $nsid }

/** A proposed answer to a question */
type Main = {
  $type: 'fyi.questionable.answer'

  /**
   * Indicates the question to which this is a proposed answer to
   */
  question: RepoStrongRef.Main
  createdAt: l.DatetimeString
  content: RichtextContent.Main
  languages?: l.LanguageString[]
}

export type { Main }

/** A proposed answer to a question */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    question: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    createdAt: l.string({ format: 'datetime' }),
    content: l.ref<RichtextContent.Main>((() => RichtextContent.main) as any),
    languages: l.optional(
      l.array(l.string({ format: 'language' }), { maxLength: 3 }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
