/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'
import * as ActorProfile from './actor/profile.defs.js'

const $nsid = 'fyi.questionable.question'

export { $nsid }

/** A question asked on questionable.fyi */
type Main = {
  $type: 'fyi.questionable.question'
  createdAt: l.DatetimeString

  /**
   * A short summary of the question
   */
  summary: string

  /**
   * The full text of the question
   */
  text: string

  /**
   * Indicates human language of the primary text content.
   */
  languages?: l.LanguageString[]

  /**
   * The answers selected by the author of the question as answering the question
   */
  answers?: RepoStrongRef.Main[]
  context?: l.TypedRef<ActorProfile.Main> | l.TypedObject
}

export type { Main }

/** A question asked on questionable.fyi */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    createdAt: l.string({ format: 'datetime' }),
    summary: l.string({ maxGraphemes: 300, maxLength: 3000, minLength: 1 }),
    text: l.string({ minLength: 1, maxGraphemes: 10000, maxLength: 10000 }),
    languages: l.optional(
      l.array(l.string({ format: 'language' }), { maxLength: 3 }),
    ),
    answers: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any), {
        maxLength: 10,
      }),
    ),
    context: l.optional(
      l.typedUnion(
        [l.typedRef<ActorProfile.Main>((() => ActorProfile.main) as any)],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
