/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'fyi.questionable.selectedAnswer'

export { $nsid }

/** Marks an answer as answering a given question */
type Main = {
  $type: 'fyi.questionable.selectedAnswer'
  questionRef: RepoStrongRef.Main
  answerRef: RepoStrongRef.Main

  /**
   * Client-declared timestamp when this vote was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Marks an answer as answering a given question */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    questionRef: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    answerRef: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
