/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextText from './text.defs.js'
import * as RichtextCode from './code.defs.js'
import * as RichtextHeader from './header.defs.js'
import * as RichtextHorizontalRule from './horizontalRule.defs.js'
import * as RichtextList from './list.defs.js'

const $nsid = 'fyi.questionable.richtext.blockquote'

export { $nsid }

type Main = {
  $type?: 'fyi.questionable.richtext.blockquote'
  plaintext?: string

  /**
   * Content blocks inside the blockquote
   */
  items: (
    | l.$Typed<RichtextText.Main>
    | l.$Typed<Main>
    | l.$Typed<RichtextCode.Main>
    | l.$Typed<RichtextHeader.Main>
    | l.$Typed<RichtextHorizontalRule.Main>
    | l.$Typed<RichtextList.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    plaintext: l.optional(l.string()),
    items: l.array(
      l.typedUnion(
        [
          l.typedRef<RichtextText.Main>((() => RichtextText.main) as any),
          l.typedRef<Main>((() => main) as any),
          l.typedRef<RichtextCode.Main>((() => RichtextCode.main) as any),
          l.typedRef<RichtextHeader.Main>((() => RichtextHeader.main) as any),
          l.typedRef<RichtextHorizontalRule.Main>(
            (() => RichtextHorizontalRule.main) as any,
          ),
          l.typedRef<RichtextList.Main>((() => RichtextList.main) as any),
        ],
        false,
      ),
      { maxLength: 500 },
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
