/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.questionable.richtext.code'

export { $nsid }

type Main = {
  $type?: 'fyi.questionable.richtext.code'
  language?: string
  plaintext: string
  syntaxHighlightingTheme?: string
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    language: l.optional(
      l.string({ maxGraphemes: 500, maxLength: 500, minLength: 1 }),
    ),
    plaintext: l.string(),
    syntaxHighlightingTheme: l.optional(
      l.string({ maxGraphemes: 500, maxLength: 500, minLength: 1 }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
