/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextText from './text.defs.js'
import * as RichtextBlockquote from './blockquote.defs.js'
import * as RichtextBskyPost from './bskyPost.defs.js'
import * as RichtextCode from './code.defs.js'
import * as RichtextHeader from './header.defs.js'
import * as RichtextHorizontalRule from './horizontalRule.defs.js'
import * as RichtextImage from './image.defs.js'
import * as RichtextMath from './math.defs.js'
import * as RichtextList from './list.defs.js'
import * as RichtextWebsite from './website.defs.js'

const $nsid = 'fyi.questionable.richtext.content'

export { $nsid }

type Main = {
  $type?: 'fyi.questionable.richtext.content'

  /**
   * Array of content blocks
   */
  items: (
    | l.$Typed<RichtextText.Main>
    | l.$Typed<RichtextBlockquote.Main>
    | l.$Typed<RichtextBskyPost.Main>
    | l.$Typed<RichtextCode.Main>
    | l.$Typed<RichtextHeader.Main>
    | l.$Typed<RichtextHorizontalRule.Main>
    | l.$Typed<RichtextImage.Main>
    | l.$Typed<RichtextMath.Main>
    | l.$Typed<RichtextText.Main>
    | l.$Typed<RichtextList.Main>
    | l.$Typed<RichtextWebsite.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    items: l.array(
      l.typedUnion(
        [
          l.typedRef<RichtextText.Main>((() => RichtextText.main) as any),
          l.typedRef<RichtextBlockquote.Main>(
            (() => RichtextBlockquote.main) as any,
          ),
          l.typedRef<RichtextBskyPost.Main>(
            (() => RichtextBskyPost.main) as any,
          ),
          l.typedRef<RichtextCode.Main>((() => RichtextCode.main) as any),
          l.typedRef<RichtextHeader.Main>((() => RichtextHeader.main) as any),
          l.typedRef<RichtextHorizontalRule.Main>(
            (() => RichtextHorizontalRule.main) as any,
          ),
          l.typedRef<RichtextImage.Main>((() => RichtextImage.main) as any),
          l.typedRef<RichtextMath.Main>((() => RichtextMath.main) as any),
          l.typedRef<RichtextText.Main>((() => RichtextText.main) as any),
          l.typedRef<RichtextList.Main>((() => RichtextList.main) as any),
          l.typedRef<RichtextWebsite.Main>((() => RichtextWebsite.main) as any),
        ],
        false,
      ),
      { maxLength: 1000 },
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
