/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.questionable.richtext.facet'

export { $nsid }

/** Annotation of a sub-string within rich text. */
type Main = {
  $type?: 'fyi.questionable.richtext.facet'
  features: (
    | l.TypedRef<Link>
    | l.TypedRef<Mention>
    | l.TypedRef<Code>
    | l.TypedRef<Highlight>
    | l.TypedRef<Underline>
    | l.TypedRef<Strikethrough>
    | l.TypedRef<Bold>
    | l.TypedRef<Italic>
    | l.TypedObject
  )[]
  index: ByteSlice
}

export type { Main }

/** Annotation of a sub-string within rich text. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    features: l.array(
      l.typedUnion(
        [
          l.typedRef<Link>((() => link) as any),
          l.typedRef<Mention>((() => mention) as any),
          l.typedRef<Code>((() => code) as any),
          l.typedRef<Highlight>((() => highlight) as any),
          l.typedRef<Underline>((() => underline) as any),
          l.typedRef<Strikethrough>((() => strikethrough) as any),
          l.typedRef<Bold>((() => bold) as any),
          l.typedRef<Italic>((() => italic) as any),
        ],
        false,
      ),
    ),
    index: l.ref<ByteSlice>((() => byteSlice) as any),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets. */
type ByteSlice = {
  $type?: 'fyi.questionable.richtext.facet#byteSlice'
  byteEnd: number
  byteStart: number
}

export type { ByteSlice }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets. */
const byteSlice = l.typedObject<ByteSlice>(
  $nsid,
  'byteSlice',
  l.object({
    byteEnd: l.integer({ minimum: 0 }),
    byteStart: l.integer({ minimum: 0 }),
  }),
)

export { byteSlice }

/** Facet feature for mentioning a did. */
type Mention = {
  $type?: 'fyi.questionable.richtext.facet#mention'
  did: l.DidString
}

export type { Mention }

/** Facet feature for mentioning a did. */
const mention = l.typedObject<Mention>(
  $nsid,
  'mention',
  l.object({ did: l.string({ format: 'did' }) }),
)

export { mention }

/** Facet feature for bold text */
type Bold = { $type?: 'fyi.questionable.richtext.facet#bold' }

export type { Bold }

/** Facet feature for bold text */
const bold = l.typedObject<Bold>($nsid, 'bold', l.object({}))

export { bold }

/** Facet feature for inline code. */
type Code = { $type?: 'fyi.questionable.richtext.facet#code' }

export type { Code }

/** Facet feature for inline code. */
const code = l.typedObject<Code>($nsid, 'code', l.object({}))

export { code }

/** Facet feature for highlighted text. */
type Highlight = { $type?: 'fyi.questionable.richtext.facet#highlight' }

export type { Highlight }

/** Facet feature for highlighted text. */
const highlight = l.typedObject<Highlight>($nsid, 'highlight', l.object({}))

export { highlight }

/** Facet feature for italic text */
type Italic = { $type?: 'fyi.questionable.richtext.facet#italic' }

export type { Italic }

/** Facet feature for italic text */
const italic = l.typedObject<Italic>($nsid, 'italic', l.object({}))

export { italic }

/** Facet feature for strikethrough markup */
type Strikethrough = { $type?: 'fyi.questionable.richtext.facet#strikethrough' }

export type { Strikethrough }

/** Facet feature for strikethrough markup */
const strikethrough = l.typedObject<Strikethrough>(
  $nsid,
  'strikethrough',
  l.object({}),
)

export { strikethrough }

/** Facet feature for underline markup */
type Underline = { $type?: 'fyi.questionable.richtext.facet#underline' }

export type { Underline }

/** Facet feature for underline markup */
const underline = l.typedObject<Underline>($nsid, 'underline', l.object({}))

export { underline }

/** Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL. */
type Link = { $type?: 'fyi.questionable.richtext.facet#link'; uri: l.UriString }

export type { Link }

/** Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL. */
const link = l.typedObject<Link>(
  $nsid,
  'link',
  l.object({ uri: l.string({ format: 'uri' }) }),
)

export { link }
