/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextFacet from './facet.defs.js'

const $nsid = 'fyi.questionable.richtext.header'

export { $nsid }

type Main = {
  $type?: 'fyi.questionable.richtext.header'
  facets?: RichtextFacet.Main[]
  level: number
  plaintext: string
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    facets: l.optional(
      l.array(l.ref<RichtextFacet.Main>((() => RichtextFacet.main) as any)),
    ),
    level: l.integer({ maximum: 6, minimum: 1 }),
    plaintext: l.string({ maxGraphemes: 1000, maxLength: 2000 }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
