/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'fyi.questionable.richtext.image'

export { $nsid }

type AspectRatio = {
  $type?: 'fyi.questionable.richtext.image#aspectRatio'
  height: number
  width: number
}

export type { AspectRatio }

const aspectRatio = l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  l.object({ height: l.integer(), width: l.integer() }),
)

export { aspectRatio }

type Main = {
  $type?: 'fyi.questionable.richtext.image'

  /**
   * Alt text description of the image, for accessibility.
   */
  alt?: string
  aspectRatio: AspectRatio
  image: l.BlobRef
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    alt: l.optional(l.string({ maxGraphemes: 3000, maxLength: 3000 })),
    aspectRatio: l.ref<AspectRatio>((() => aspectRatio) as any),
    image: l.blob({
      accept: ['image/*'],
      maxSize: 1000000,
      allowLegacy: false,
    }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
