/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Home: () => import('#controllers/home_controller'),
  Interviews: () => import('#controllers/interviews_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
  api: {
    Asks: () => import('#controllers/api/asks_controller'),
  },
}
